### ISSUE TITLE
[question] passing the levels

### ISSUE THREAD

**Issue by MrNewb** [WeaselRP/weasel-crafting#2]
could you post a example on how you are passing the levels in an event?

**Comment by MrNewb** [comment]
something like this seems to work, just curious if im doing it correctly. TriggerEvent('weasel-crafting:openMenu', '5')

**Comment by Trey2k** [comment]
The level is passed in the event as a number yes, https://github.com/WeaselRP/weasel-crafting/blob/a6ed78b4a454cd2ce1210bc2a729f62948bfc5a5/server/main.lua#L16
