### ISSUE TITLE
[Q] Job Requirements

### ISSUE THREAD

**Issue by SantyR0** [WeaselRP/weasel-crafting#5]
Sorry for msg, i know this is already not active but i just wanna ask if u have idea how to put job requirements?

**Comment by Trey2k** [comment]
To add job requirements you would want to create a custom crafting menu probably from the jobs menu using this trigger ```TriggerEvent("weasel-crafting:customMenu", (IItems structured exactly the same as in the config but for the custom menu), (lvl))```

**Comment by SantyR0** [comment]
my bad can't make it work, do u have a example? thanks for taking time replying.

i tried it like this, but it keeps giving me errors. I put it on policejob\client\main.lua

local crafttables = {
    1917885559
}

exports['qtarget']:AddTargetModel(crafttables, {
    options = {
        {
            event = "weasel-crafting:mechcraft",            
            icon = "fas fa-tools",
            label = "Crafting Table"
        },
    },
    distance = 2
})
RegisterNetEvent("weasel-crafting:mechcraft")
AddEventHandler("weasel-crafting:mechcraft", function()
    TriggerEvent("weasel-crafting:mechcraft", ({
        Name = "lockpick",
        DisplayName = "Lockpick",
        Quantity = 2,
        MetaData = {},
        Time = 10000,
        Level = 1,
        Recipe = {
            {'Schroot', 'scrapmetal', 10, {}, true},
            {'Rubber', 'rubber', 2, {}, true},
            {'Plastic', 'plastic', 4, {}, true},
            {'Staal', 'steel', 3, {}, true},
    }}))
end)

**Comment by Trey2k** [comment]
That looks like the qtarget example, are you using qtarget?

**Comment by SantyR0** [comment]
Yes. I'm sorry for too many question, but trying to learn. I'm trying to make a craftable items per job.

**Comment by Trey2k** [comment]
I have attached one of our resources that used a custom crafting menu. You would want to use the same method for the police job.
[weasel-selling.zip](https://github.com/WeaselRP/weasel-crafting/files/8503776/weasel-selling.zip)

**Comment by SantyR0** [comment]
Wow thanks, this is good. But I need to make it only accessible for certain job. Is there any way to make it that way?

**Comment by Trey2k** [comment]
Yes, if you do it exactly the same as the file I sent you but move the event trigger to the jobs menu. Only that job will be able to access it.

**Comment by SantyR0** [comment]
Should it be something like this? My bad, I'm new to this.

esx_policejob/client/main.lua
					

> if action == 'identity_card' then
> 						TriggerEvent("weasel-crafting:openShop", v.Shop)

then

esx_policejob/config.lua

Config.OxInventory                = ESX.GetConfig().OxInventory


> local shopItems = {
>     WeedShop = {
>         {
>             Name = "weed",
>             DisplayName = "Weed",
>             Quantity = 1,
>             MetaData = {},
>             Time = 10000,
>             Level = 1,
>             Recipe = {
>                 {'money', 'money', 1, {}, true}
>                 -- Displayname, Item Name, Amount needed, metadata, consumed
>             }
>         },
> 	}
> }
